return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
      color_overrides = {
        all = {
          rosewater = "#F5F2F0",
          flamingo = "#F5F2F0",
          pink = "#BBA4E7",
          mauve = "#B28EE8",
          red = "#EC6E5D",
          maroon = "#EC6E5D",
          peach = "#E0A96D",
          yellow = "#E0A96D",
          green = "#A6E3A1",
          teal = "#3C5865",
          sky = "#3C5865",
          sapphire = "#3C5865",
          blue = "#3C5865",
          lavender = "#F5F2F0",
          text = "#F5F2F0",
          subtext1 = "#D3C8C0",
          subtext0 = "#C5BCB4",
          overlay2 = "#88929A",
          overlay1 = "#6D818C",
          overlay0 = "#5A6D77",
          surface2 = "#353B42",
          surface1 = "#2B3035",
          surface0 = "#22262A",
          base = "#15171A",
          mantle = "#15171A",
          crust = "#15171A",
        },
      },
      custom_highlights = function(colors)
        return {
          Comment = { fg = colors.overlay1, italic = true },
          ["@comment"] = { fg = colors.overlay1, italic = true },
          Keyword = { fg = colors.mauve, bold = true },
          ["@keyword"] = { fg = colors.mauve, bold = true },
          Function = { fg = colors.pink },
          ["@function"] = { fg = colors.pink },
          String = { fg = colors.text },
          ["@string"] = { fg = colors.text },
          Type = { fg = colors.teal },
          ["@type"] = { fg = colors.teal },
          Number = { fg = colors.peach },
          ["@number"] = { fg = colors.peach },
          Boolean = { fg = colors.peach },
          ["@boolean"] = { fg = colors.peach },
          Constant = { fg = colors.text },
          ["@constant"] = { fg = colors.text },
          Property = { fg = colors.subtext0 },
          ["@property"] = { fg = colors.subtext0 },
          Operator = { fg = colors.teal },
          ["@operator"] = { fg = colors.teal },
          Delimiter = { fg = colors.overlay1 },
          ["@punctuation.delimiter"] = { fg = colors.overlay1 },
          Tag = { fg = colors.mauve },
          ["@tag"] = { fg = colors.mauve },
          ["@tag.attribute"] = { fg = colors.teal },
        }
      end,
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}
