return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
      color_overrides = {
        all = {
          rosewater = "#F0EDEB",
          flamingo = "#F0EDEB",
          pink = "#CFB5FF",
          mauve = "#B28EE8",
          red = "#C18F9D",
          maroon = "#C18F9D",
          peach = "#C8B18E",
          yellow = "#C8B18E",
          green = "#A8C7B0",
          teal = "#9BAED1",
          sky = "#9BAED1",
          sapphire = "#9BAED1",
          blue = "#9BAED1",
          lavender = "#F0EDEB",
          text = "#F0EDEB",
          subtext1 = "#D2CFCE",
          subtext0 = "#C3C1C2",
          overlay2 = "#92929C",
          overlay1 = "#7C7E89",
          overlay0 = "#6A6C77",
          surface2 = "#4A4C57",
          surface1 = "#27292C",
          surface0 = "#27292C",
          base = "#27292C",
          mantle = "#27292C",
          crust = "#27292C",
        },
      },
      custom_highlights = function(colors)
        return {
          Comment = { fg = colors.overlay1, italic = true },
          ["@comment"] = { fg = colors.overlay1, italic = true },
          Keyword = { fg = colors.mauve, bold = true },
          ["@keyword"] = { fg = colors.mauve, bold = true },
          Function = { fg = colors.pink },
          ["@function"] = { fg = colors.pink },
          String = { fg = colors.green },
          ["@string"] = { fg = colors.green },
          Type = { fg = colors.teal },
          ["@type"] = { fg = colors.teal },
          Number = { fg = colors.peach },
          ["@number"] = { fg = colors.peach },
          Boolean = { fg = colors.overlay2 },
          ["@boolean"] = { fg = colors.overlay2 },
          Constant = { fg = colors.text },
          ["@constant"] = { fg = colors.text },
          Property = { fg = colors.subtext0 },
          ["@property"] = { fg = colors.subtext0 },
          Operator = { fg = colors.teal },
          ["@operator"] = { fg = colors.teal },
          Delimiter = { fg = colors.overlay1 },
          ["@punctuation.delimiter"] = { fg = colors.overlay1 },
          Tag = { fg = colors.mauve },
          ["@tag"] = { fg = colors.mauve },
          ["@tag.attribute"] = { fg = colors.teal },
          Identifier = { fg = colors.text },
          ["@variable"] = { fg = colors.text },
          ["@variable.parameter"] = { fg = colors.subtext1 },
          ["@function.call"] = { fg = colors.pink },
          ["@function.method"] = { fg = colors.pink },
          ["@string.escape"] = { fg = colors.peach },
          ["@number.float"] = { fg = colors.peach },
          ["@type.builtin"] = { fg = colors.sky },
          Normal = { bg = "NONE" },
          NormalNC = { bg = "NONE" },
          NormalFloat = { bg = "NONE" },
          SignColumn = { bg = "NONE" },
          FoldColumn = { bg = "NONE" },
          LineNr = { fg = colors.overlay0, bg = "NONE" },
          CursorLineNr = { fg = colors.text, bg = "NONE" },
          EndOfBuffer = { fg = colors.overlay0, bg = "NONE" },
          StatusLine = { bg = "NONE" },
          StatusLineNC = { bg = "NONE" },
          WinSeparator = { fg = colors.overlay0, bg = "NONE" },
          FloatBorder = { fg = colors.mauve, bg = "NONE" },
        }
      end,
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}
