# $schema = 'https://starship.rs/config-schema.json'

format = """
[](color_one)\
$os\
$username\
[](bg:color_two fg:color_one)\
$directory\
[](bg:color_three fg:color_two)\
$git_branch\
$git_status\
[](bg:color_four fg:color_three)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$docker_context\
$conda\
[](bg:color_one fg:color_four)\
$cmd_duration\
[](fg:color_one)\
\n$character"""

palette = "overcast"

[palettes.overcast]
color_one = '#30323D'
color_two = '#5B5E6B'
color_three = '#B28EE8'
color_four = '#444752'
text_light = '#D0CCC7'

[os]
disabled = false
style = 'bg:color_one fg:text_light'
format = '[$symbol ]($style)'

[os.symbols]
Macos = ''

[username]
show_always = true
style_user = 'bg:color_one fg:text_light bold'
style_root = 'bg:color_one fg:text_light bold'
format = '[$user ]($style)'

[directory]
style = 'bg:color_two fg:text_light'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = 'bg:color_three fg:color_one'
format = '[[ $symbol $branch ](fg:color_one bg:color_three)]($style)'

[git_status]
style = 'bg:color_three fg:color_one'
format = '[[($all_status$ahead_behind )](fg:color_one bg:color_three)]($style)'

[c]
symbol = ' '
style = 'bg:color_four fg:text_light'
format = '[[ $symbol ($version) ](fg:text_light bg:color_four)]($style)'

[rust]
symbol = ''
style = 'bg:color_four fg:text_light'
format = '[[ $symbol ($version) ](fg:text_light bg:color_four)]($style)'

[golang]
symbol = ''
style = 'bg:color_four fg:text_light'
format = '[[ $symbol ($version) ](fg:text_light bg:color_four)]($style)'

[nodejs]
symbol = ''
style = 'bg:color_four fg:text_light'
format = '[[ $symbol ($version) ](fg:text_light bg:color_four)]($style)'

[bun]
symbol = '🥟'
style = 'bg:color_four fg:text_light'
format = '[[ $symbol ($version) ](fg:text_light bg:color_four)]($style)'

[cmd_duration]
min_time = 0
style = 'bg:color_one fg:text_light'
format = '[[  $duration ](fg:text_light bg:color_one)]($style)'

[character]
success_symbol = '[❯](color_three)'
error_symbol = '[❯](color_three)'
vimcmd_symbol = '[❮](color_three)'

[docker_context]
style = 'bg:color_four fg:text_light'
symbol = '🐳'
format = '[[ $symbol $context ](fg:text_light bg:color_four)]($style)'
